FROM node:22.17.0-alpine

WORKDIR /app

COPY apps/frontend/.next/standalone ./
RUN mv -n /app/apps/frontend/* /app/apps/frontend/.* /app

COPY apps/frontend/.next/static ./.next/static/

RUN chown 1001:1001 /app  -R
USER 1001

EXPOSE 3000
ENV PORT 3000

ENTRYPOINT ["node", "/app/server.js"]
