pipeline {

    tools { 
      go '1.24.2'
     }

    agent {
      kubernetes {
        yamlFile '.devops/builder.yaml'
      }
    }

    stages {
          stage('Kaniko Build & Push Image') {
                steps {
                      container('kaniko') {
                            script {
                                  sh '''
                                  /kaniko/executor --dockerfile `pwd`.devops/docker/Dockerfile.content-service \
                                              --context `pwd` \
                                              --destination=cms-content-service:${BUILD_NUMBER}
                                  '''
                            }
                      }
                }
          }
    }
}