pipeline {
    agent any

    tools { 
      go '1.24.2'
      dockerTool true
     }

    environment {
        REGISTRY_URL = 'registry.patrick.dev.br'
        IMAGE_NAME = 'cms-content-service'
        IMAGE_TAG = 'latest'
        DOCKER_CREDENTIALS_ID = 'docker-registry'
    }

      stages {
            stage('Build Docker Image') {
                  steps {
                        script {
                              app = docker.build("cms/content-service:${env.BUILD_ID}", "-f ./.devops/docker/Dockerfile.content-service")
                        }
                  }
            }
            
            stage('Push Docker Image') {
                  steps {
                        script {
                              docker.withRegistry('https://registry.patrick.dev.br', 'docker-registry') {
                                    app.push("latest")
                                    app.push("${env.BUILD_ID}")
                              }
                        }
                  }
            }
      }
}