name: Build

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
    outputs:
      image_tag:
        description: "Image tag for publishing"
        value: ${{ jobs.build.outputs.image_tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v3

      - name: Generate Image Tag
        id: set-tag
        run: echo "image_tag=sha-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image (No push yet)
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ${{ inputs.dockerfile }}
          push: false
          load: true
