name: Reusable Deploy

on:
  workflow_call:
    inputs:
      k8s_manifest_dir:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Update image tag in manifest
        run: |
          find ${{ inputs.k8s_manifest_dir }} -type f -name "*.yaml" -exec \
            sed -i "s|${{ secrets.DOCKER_REGISTRY_URL }}/${{ inputs.image_name }}:latest|${{ secrets.DOCKER_REGISTRY_URL }}/${{ inputs.image_name }}:${{ inputs.image_tag }}|g" {} +

      - name: Apply K8s manifests
        run: |
          kubectl apply -f ${{ inputs.k8s_manifest_dir }}
